version: "3.6"
services:
  dqxtools_twitter_webhook:
    image: dqxtools_twitter_webhook
    container_name: dqxtools_twitter_webhook
    networks:
      dqxtools:
    env_file:
      - .env
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - USERS_TO_FOLLOW=${USERS_TO_FOLLOW}
      - LOG_LEVEL=${LOG_LEVEL}
      - TWITTER_IMAGE_COLLAGE_API=${TWITTER_IMAGE_COLLAGE_API}
      - DEEPL_FREE_API_KEY=${DEEPL_FREE_API_KEY}
    restart: always

networks:
  dqxtools:
    name: dqxtools
    external: true
